source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'testGitHub3_Example', :exclusive => true do
  pod "testGitHub3", :path => "../"
end

target 'testGitHub3_Tests', :exclusive => true do
  pod "testGitHub3", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
